#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("InterceptAuditDefault.Resource", IsApplication=true)]

namespace InterceptAuditDefault
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AuditApp.Android.Resource.Id.intercept_suggestion_comment = global::InterceptAuditDefault.Resource.Id.intercept_suggestion_comment;
			global::AuditApp.Android.Resource.Id.intercept_suggestion_done = global::InterceptAuditDefault.Resource.Id.intercept_suggestion_done;
			global::AuditApp.Android.Resource.Id.intercept_suggestion_header = global::InterceptAuditDefault.Resource.Id.intercept_suggestion_header;
			global::AuditApp.Android.Resource.Id.intercept_suggestion_id = global::InterceptAuditDefault.Resource.Id.intercept_suggestion_id;
			global::AuditApp.Android.Resource.Layout.intercept_suggestion_layout = global::InterceptAuditDefault.Resource.Layout.intercept_suggestion_layout;
			global::AuditApp.Android.Resource.String.library_name = global::InterceptAuditDefault.Resource.String.library_name;
			global::AuditApp.Android.Resource.Style.intercept_suggestion_background = global::InterceptAuditDefault.Resource.Style.intercept_suggestion_background;
			global::AuditApp.Android.Resource.Style.intercept_suggestion_commentstyle = global::InterceptAuditDefault.Resource.Style.intercept_suggestion_commentstyle;
			global::AuditApp.Android.Resource.Style.intercept_suggestion_donebuttonstyle = global::InterceptAuditDefault.Resource.Style.intercept_suggestion_donebuttonstyle;
			global::AuditApp.Android.Resource.Style.intercept_suggestion_headerstyle = global::InterceptAuditDefault.Resource.Style.intercept_suggestion_headerstyle;
			global::AuditApp.Android.Resource.Style.intercept_suggestion_idstyle = global::InterceptAuditDefault.Resource.Style.intercept_suggestion_idstyle;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int intercept_suggestion_comment = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int intercept_suggestion_done = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int intercept_suggestion_header = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int intercept_suggestion_id = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int myButton = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int intercept_suggestion_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050004
			public const int intercept_suggestion_background = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int intercept_suggestion_commentstyle = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int intercept_suggestion_donebuttonstyle = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int intercept_suggestion_headerstyle = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int intercept_suggestion_idstyle = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
