#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AuditApp.Android.Resource", IsApplication=false)]

namespace AuditApp.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public static int intercept_suggestion_comment = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int intercept_suggestion_done = 2131034115;
			
			// aapt resource value: 0x7f050000
			public static int intercept_suggestion_header = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int intercept_suggestion_id = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int intercept_suggestion_layout = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public static int library_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040004
			public static int intercept_suggestion_background = 2130968580;
			
			// aapt resource value: 0x7f040001
			public static int intercept_suggestion_commentstyle = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int intercept_suggestion_donebuttonstyle = 2130968578;
			
			// aapt resource value: 0x7f040000
			public static int intercept_suggestion_headerstyle = 2130968576;
			
			// aapt resource value: 0x7f040003
			public static int intercept_suggestion_idstyle = 2130968579;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
