require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "xamarin-component"

COMPONENT = "AuditApp-1.0.xam"

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "xamarin-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o -q xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do
	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{COMPONENT} \
		--name="AuditApp" \
		--summary="Prompts users to review your app. Many options and two different customizable prompts." \
		--publisher="Kevin Skrei" \
		--website="http://kevinskrei.com" \
		--details="Details.md" \
		--license="License.md" \
		--getting-started="GettingStarted.md" \
		--icon="icons/AuditApp_128x128.png" \
		--icon="icons/AuditApp_512x512.png" \
		--library="android":"AuditApp/AuditApp.Android/bin/Release/AuditApp.Android.dll" \
		--sample="Different Android Audit Type Samples. 3 different samples.":"samples/AuditSamples/AuditAppSamples/AuditAppSamples.sln" 
		END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end
